
POST https://localhost:7165/api/newtonraphson/solve
Content-Type: application/json

{
  "functionStr": "x^2 - 4*x + 3",
  "initialGuess": -5,
  "tolerance": 0.0001,
  "maxIterations": 100
}


### here use id from post request result
### 
GET https://localhost:7165/api/newtonraphson/progress/895b45fa-60ea-4602-82e7-5f0471126f14